---
title: "Лабораторная работа №1. Использование технологии Yandex Query для анализа данных сетевой активности"
author: "Поспелова Ульяна БИСО-03-20"
format: 
    md:
        output-file: README.md
editor: visual
---

## Цель работы

1. Изучить возможности технологии Yandex Query для анализа структурированных наборов данных.

2. Получить навыки построения аналитического пайплайна для анализа данных с помощью сервисов Yandex Cloud.

3. Закрепить практические навыки использования SQL для анализа данных сетевой активности в сегментированной корпоративной сети.

## Общая ситуация

Вам стали доступны данные сетевой активности в корпоративной сети компании XYZ. Данные хранятся в Yandex Object Storage. Проведите разведочный анализ данных и ответьте на вопросы.

## Задание

Используя сервис Yandex Query настроить доступ к данным, хранящимся в сервисе хранения данных Yandex Object Storage. При помощи соответствующих SQL запросов ответить на вопросы.

## Ход работы

### 1. Проверка доступности данных в Yandex Object Storage

1\. Проверим доступность данных (файл yaqry_dataset.pqt) в бакете arrow-datasets S3 хранилища Yandex Object Storage. Проверить можно просто перейдя по правильно сконструированному URL в браузере.
